server:
  port: 8081 #服务注册中心端口号
eureka:
  instance:
#    hostname: 127.0.0.1 #服务注册中心IP地址
    prefer-ip-address: true
  client:
#    registerWithEureka: true #是否向服务注册中心注册自己
#    fetchRegistry: true #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://localhost:${server.port}/eureka/
spring:
  application:
    name: eurekaServer