server:
  port: 8888

spring:
  application:
    name: config-server #应用名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/17721541089/confsvr.git #配置文件所在仓库
          search-paths: configserver
          default-label: master #配置文件分支
          username: 17721541089 #登录账号
          password: sheng6130219 #登录密码

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka      # 指向注册中心的地址

